### ISSUE TITLE
O bot é iniciado porém da erro

### ISSUE THREAD

**Issue by All4ce** [LucianoDeveloper/economy-bot#4]
**Boa noite**, estou com um problema e não consegui resolver esse.
O bot inicia certinho, instalei as dependências, porém quando uso um comando ele retorna isso aí e o bot não faz nada, só fica online, sabe oq pode ser?

``` 
node index.js
Attempting to load command background
Attempting to load command buy
Attempting to load command gacha
Attempting to load command open
Attempting to load command pescar
Attempting to load command profile
Attempting to load command work
Bot iniciado com 5 usuários, em 12 canais de 1 servidores.
(node:1661) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'cache' of undefined
    at Object.exports.run (/home/scrowzy/economy-bot-master/comandos/work.js:11:27)
    at Client.<anonymous> (/home/scrowzy/economy-bot-master/index.js:75:17)
    at Client.emit (events.js:314:20)
    at MessageCreateAction.handle (/home/scrowzy/economy-bot-master/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/scrowzy/economy-bot-master/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/scrowzy/economy-bot-master/node_modules/discord.js/src/client/websocket/WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (/home/scrowzy/economy-bot-master/node_modules/discord.js/src/client/websocket/WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (/home/scrowzy/economy-bot-master/node_modules/discord.js/src/client/websocket/WebSocketShard.js:293:10)
    at WebSocket.onMessage (/home/scrowzy/economy-bot-master/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:314:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1661) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1661) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by KamaiDev** [comment]
a versão do seu discord.js está na 12, então basta você ir na package.json
e trocar a versão 12.2.0 por 11.5.2

Em ter., 21 de jul. de 2020 às 00:29, Allaace <notifications@github.com>
escreveu:

**Comment by All4ce** [comment]
**Mesmo trocando retornou o mesmo erro.**
```
(node:14305) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'cache' of undefined
    at Object.exports.run (/home/scrowzy/economy-bot-master/comandos/work.js:11:27)
    at Client.<anonymous> (/home/scrowzy/economy-bot-master/index.js:75:17)
    at Client.emit (events.js:314:20)
    at MessageCreateAction.handle (/home/scrowzy/economy-bot-master/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/scrowzy/economy-bot-master/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/scrowzy/economy-bot-master/node_modules/discord.js/src/client/websocket/WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (/home/scrowzy/economy-bot-master/node_modules/discord.js/src/client/websocket/WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (/home/scrowzy/economy-bot-master/node_modules/discord.js/src/client/websocket/WebSocketShard.js:293:10)
    at WebSocket.onMessage (/home/scrowzy/economy-bot-master/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:314:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14305) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14305) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by KamaiDev** [comment]
O erro "cache" ali vem dos ".cache.<alguma coisa" do código. Para corrigir,
basta apagar os ".cache" ou atualizar a versão do seu discord.js para a
versão 12


Em qui, 23 de jul de 2020 00:23, Allaace <notifications@github.com>
escreveu:

**Comment by rlimaoficial** [comment]
Apagando o ".cache", o ".find" fica indefinido,

**Comment by pipoqueiro1** [comment]
mano seu bot ta incrivel de vdd to me inspirando para fazer um sistema de economia, mais ta dando erro de cache nao definido, ja tentei definir e mesmo assim da erro

**Comment by KamaiDev** [comment]
Poderia enviar a mensagem de erro que apareceu? Desculpe pela resposta demorada. Tive uns imprevistos e acabei perdendo a noção de tempo e minhas redes sociais ficaram paradas.
